apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tasktime.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tasktime.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "tasktime.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        {{- include "tasktime.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
      - name: ghcr-pull-secret
      containers:
      - name: tasktime
        image: "{{ .Values.image.repository }}:{{ .Values.image.version }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        envFrom:
        - configMapRef:
            name: {{ include "tasktime.fullname" . }}-config
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 10 }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
